modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Easy-Model-Entities/issues"

[[mods]]
modId = "easy_model_entities"
version = "${file.jarVersion}"
displayTest = "MATCH_VERSION"
displayName = "Easy Model Entities"
displayURL = "https://curseforge.com/minecraft/mc-mods/easy-model-entities"
authors = "Markus Bordihn"
description = '''Turn Blockbench models into simple Minecraft entities without writing Java code.'''

[[dependencies.easy_model_entities]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_model_entities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
