# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Ghost Reference Index
ghostRefIndex=D:/GitHub/MarkusBordihn/Ghost-Reference-Index/gradle/ghost-ref-minecraft-1.20.1.gradle
# Project
version=2.2.0
group=de.markusbordihn.easymodelentities
vendor_name=markusbordihn
# Mod
mod_id=easy_model_entities
mod_name=Easy Model Entities
mod_author=Markus Bordihn
mod_namespace=easymodelentities
# Common
minecraft_version=1.20.1
# Forge Mod Loader
forge_version=47.4.10
forge_min_version=47.3.11
# Fabric Mod Loader
fabric_version=0.92.9+1.20.1
fabric_api_min_version=0.92.9+1.20.1
fabric_loader_version=0.19.3
fabric_loader_min_version=0.15.0
fabric_loom=1.9-SNAPSHOT
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=1539533
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=ngLoLP1P
modrinth_api_token=Never put your token here!
