# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
# Ghost Reference Index
ghostRefIndex=D:/GitHub/MarkusBordihn/Ghost-Reference-Index/gradle/ghost-ref-minecraft-1.21.11.gradle
# Project
version=2.3.0
group=de.markusbordihn.easymodelentities
vendor_name=markusbordihn
# Mod
mod_id=easy_model_entities
mod_name=Easy Model Entities
mod_author=Markus Bordihn
mod_namespace=easymodelentities
# Common
minecraft_version=1.21.11
neo_form_version=1.21.11-20251209.172050
# Forge Mod Loader
forge_version=61.2.1
forge_min_version=61.2.0
# Fabric Mod Loader
fabric_version=0.141.3+1.21.11
fabric_api_min_version=0.141.3+1.21.11
fabric_loader_version=0.18.4
fabric_loader_min_version=0.18.0
fabric_loom=1.15-SNAPSHOT
# NeoForge Mod Loader
neoforge_version=21.11.42
neoforge_min_version=21.11.0
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=1539533
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=ngLoLP1P
modrinth_api_token=Never put your token here!
