plugins {
  id 'maven-publish'
  id 'net.minecraftforge.gradle' version '6.+'
  id 'com.matthewprenger.cursegradle' version '1.4.0'
  id 'nu.studer.credentials' version '3.0'
  id "com.modrinth.minotaur" version "2.+"
}

apply plugin: 'net.minecraftforge.gradle'

base {
  archivesName = "${mod_id}-forge-${minecraft_version}"
}

publishing {
  publications {
    register('mavenJava', MavenPublication) {
      artifactId = base.archivesName.get()
      artifact tasks.named('jar')
    }
  }
}

minecraft {
  mappings channel: 'official', version: "${project.minecraft_version}"

  accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")

  runs {
    client {
      workingDirectory project.file('run/client')
      property 'forge.logging.markers', 'REGISTRIES'
      property 'forge.logging.console.level', 'debug'
      property 'forge.enabledGameTestNamespaces', "${project.mod_id}"
      mods {
        "${project.mod_id}" { source sourceSets.main }
      }
    }

    server {
      workingDirectory project.file('run/server')
      property 'forge.logging.markers', 'REGISTRIES'
      property 'forge.logging.console.level', 'debug'
      property 'forge.enabledGameTestNamespaces', "${project.mod_id}"
      mods {
        "${project.mod_id}" { source sourceSets.main }
      }
    }

    gameTestServer {
      workingDirectory project.file('run/gametestserver')
      property 'forge.logging.markers', 'REGISTRIES'
      property 'forge.logging.console.level', 'debug'
      property 'forge.enabledGameTestNamespaces', "${project.mod_id}"
      mods {
        "${project.mod_id}" { source sourceSets.main }
      }
    }
  }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
  minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

  implementation project(":Common")

  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
  source(project(":Common").sourceSets.main.allSource)
}

processResources {
  from project(":Common").sourceSets.main.resources
}

tasks.named('jar', Jar).configure {
  manifest {
    attributes([
        "Specification-Title"     : "${project.mod_name}",
        "Specification-Vendor"    : "${project.vendor_name}",
        "Specification-Version"   : "1",
        "Implementation-Title"    : project.name,
        "Implementation-Version"  : "${project.version}",
        "Implementation-Vendor"   : "${project.mod_id}",
        "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
    ])
  }

  finalizedBy 'reobfJar'
}

tasks.named('build') {
  dependsOn 'reobfJar'
}

test {
  useJUnitPlatform()
}

if (project.hasProperty('curseforge_project_id') && project.curseforge_project_id) {
  curseforge {
    apiKey = "${credentials.forKey('curseforge_api_token')}"
    project {
      id = "${project.curseforge_project_id}"
      changelog = rootProject.file("CHANGELOG.md")
      changelogType = 'markdown'
      releaseType = "${project.curseforge_release_type}"
      addGameVersion("${project.minecraft_version}")
      addGameVersion("Forge")
      addGameVersion("NeoForge")
      mainArtifact(jar)
    }
  }
}

if (project.hasProperty('modrinth_project_id') && project.modrinth_project_id) {
  modrinth {
    token = "${credentials.forKey('modrinth_api_token')}"
    projectId = "${project.modrinth_project_id}"
    versionNumber = "${project.version}"
    versionType = "${project.modrinth_release_type}"
    versionName = "${project.mod_name} ${project.version}"
    changelog = rootProject.file("CHANGELOG.md").text
    uploadFile = jar
    gameVersions = ["${project.minecraft_version}"]
    loaders = ["forge", "neoforge"]
  }
}
