modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Easy-Model-Entities/issues"

[[mods]]
modId = "easy_model_entities"
version = "${file.jarVersion}"
displayName = "Easy Model Entities"
displayURL = "https://curseforge.com/minecraft/mc-mods/easy-model-entities"
authors = "Markus Bordihn"
description = '''Turn Blockbench models into simple Minecraft entities without writing Java code.'''

[[dependencies.easy_model_entities]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_model_entities]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"
